-- migrate:up
ALTER TABLE servers ADD COLUMN IF NOT EXISTS compute_type TEXT NOT NULL DEFAULT 'gpu';
ALTER TABLE servers ADD COLUMN IF NOT EXISTS cpu_count INTEGER;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS ram_gb INTEGER;
ALTER TABLE servers ADD COLUMN IF NOT EXISTS benchmark_score DOUBLE PRECISION;
ALTER TABLE servers ALTER COLUMN gpu_count DROP NOT NULL;
ALTER TABLE servers ALTER COLUMN cpu_per_gpu DROP NOT NULL;
ALTER TABLE servers ALTER COLUMN memory_per_gpu DROP NOT NULL;

ALTER TABLE chutes ADD COLUMN IF NOT EXISTS compute_type TEXT NOT NULL DEFAULT 'gpu';
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS cpu_cores INTEGER;
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS ram_gb INTEGER;
ALTER TABLE chutes ADD COLUMN IF NOT EXISTS min_benchmark_score DOUBLE PRECISION;

-- migrate:down
ALTER TABLE chutes DROP COLUMN IF EXISTS min_benchmark_score;
ALTER TABLE chutes DROP COLUMN IF EXISTS ram_gb;
ALTER TABLE chutes DROP COLUMN IF EXISTS cpu_cores;
ALTER TABLE chutes DROP COLUMN IF EXISTS compute_type;

ALTER TABLE servers DROP COLUMN IF EXISTS benchmark_score;
ALTER TABLE servers DROP COLUMN IF EXISTS ram_gb;
ALTER TABLE servers DROP COLUMN IF EXISTS cpu_count;
ALTER TABLE servers DROP COLUMN IF EXISTS compute_type;
