#!/bin/sh
# Vendored from the killall helper generated by the K3s v1.33.1+k3s1 install script.
# This exact file is checksum-pinned by the role and the cutover runtime.

[ "$(id -u)" -eq 0 ] || exec sudo --preserve-env=K3S_DATA_DIR "$0" "$@"

K3S_DATA_DIR=${K3S_DATA_DIR:-/var/lib/rancher/k3s}
for bin in "${K3S_DATA_DIR}"/data/**/bin/; do
    [ -d "$bin" ] && PATH=$PATH:$bin:$bin/aux
done
export PATH

for service in /etc/systemd/system/k3s*.service; do
    [ -s "$service" ] && systemctl stop "$(basename "$service")"
done
for service in /etc/init.d/k3s*; do
    [ -x "$service" ] && "$service" stop
done

pschildren() {
    ps -e -o ppid= -o pid= |
        sed -e 's/^\s*//g; s/\s\s*/\t/g;' |
        grep -w "^$1" |
        cut -f2
}

pstree() {
    for pid in "$@"; do
        echo "$pid"
        for child in $(pschildren "$pid"); do
            pstree "$child"
        done
    done
}

killtree() {
    # A missing process is already quiesced.
    # shellcheck disable=SC2046
    kill -9 $(pstree "$@") 2>/dev/null || true
}

getshims() {
    ps -e -o pid= -o args= |
        sed -e 's/^ *//; s/\s\s*/\t/;' |
        grep -w "${K3S_DATA_DIR}"'/data/[^/]*/bin/containerd-shim' |
        cut -f1
}

# shellcheck disable=SC2046
killtree $(getshims)

do_unmount_and_remove() {
    while read -r _ path _; do
        case "$path" in
            "$1"*) echo "$path" ;;
        esac
    done < /proc/self/mounts |
        sort -r |
        xargs -r -t -n 1 sh -c 'umount -f "$0" && rm -rf "$0"'
}

do_unmount_and_remove /run/k3s
do_unmount_and_remove /var/lib/kubelet/pods
do_unmount_and_remove /var/lib/kubelet/plugins
do_unmount_and_remove /run/netns/cni-

ip netns show 2>/dev/null |
    grep cni- |
    xargs -r -t -n 1 ip netns delete || true

ip link show 2>/dev/null |
    grep 'master cni0' |
    while read -r _ iface _; do
        iface=${iface%%@*}
        [ -z "$iface" ] || ip link delete "$iface"
    done
ip link delete cni0 2>/dev/null || true
ip link delete flannel.1 2>/dev/null || true
ip link delete flannel-v6.1 2>/dev/null || true
ip link delete kube-ipvs0 2>/dev/null || true
ip link delete flannel-wg 2>/dev/null || true
ip link delete flannel-wg-v6 2>/dev/null || true

rm -rf /var/lib/cni/
iptables-save | grep -v KUBE- | grep -v CNI- | grep -iv flannel | iptables-restore || true
ip6tables-save | grep -v KUBE- | grep -v CNI- | grep -iv flannel | ip6tables-restore || true

exit 0
