---
apiVersion: v1
kind: Secret
metadata:
  name: miner-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- $minerCredentials := lookup "v1" "Secret" .Release.Namespace "miner-credentials" }}
  owner: {{ if $minerCredentials }}{{ index $minerCredentials.data "owner" }}{{ else }}{{ .Values.minerCredentials.ownerSs58 | b64enc | quote }}{{ end }}