{{- $owner := "" -}}
{{- $minerCredentials := lookup "v1" "Secret" .Release.Namespace "miner-credentials" -}}
{{- if and $minerCredentials $minerCredentials.data (hasKey $minerCredentials.data "owner") (ne (index $minerCredentials.data "owner") "") -}}
{{- $owner = index $minerCredentials.data "owner" -}}
{{- else -}}
{{- $configuredOwner := required "minerCredentials.ownerSs58 is required" .Values.minerCredentials.ownerSs58 -}}
{{- $owner = $configuredOwner | b64enc -}}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: miner-credentials
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  owner: {{ $owner | quote }}
