- name: Read hotkey file
  ansible.builtin.slurp:
    src: "{{ hotkey_path }}"
  delegate_to: localhost
  become: false
  register: hotkey_content
  no_log: true

- name: Extract credentials
  ansible.builtin.set_fact:
    miner_credentials:
      owner_ss58: "{{ (hotkey_content.content | b64decode | from_json).ss58Address }}"
  no_log: true

- name: Distribute credentials to all cluster nodes
  ansible.builtin.set_fact:
    miner_owner_ss58: "{{ miner_credentials.owner_ss58 }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['control'] + groups['workers'] }}"
  no_log: true